# Generated by Django 2.2.7 on 2020-05-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_a', models.DateField(auto_now_add=True, verbose_name='Fecha Apertura')),
                ('fecha_c', models.DateField(auto_now=True, verbose_name='Fecha Cierre')),
                ('hora_a', models.TimeField(auto_now_add=True, verbose_name='Hora Apertura')),
                ('hora_c', models.TimeField(auto_now=True, verbose_name='Hora Apertura')),
                ('estado', models.PositiveSmallIntegerField(default=1, verbose_name='Estado')),
                ('saldo_a', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Apertura')),
                ('saldo_c', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Cierre')),
                ('caudal_a', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Caudal Inicial')),
                ('caudal_c', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Caudal Cierre')),
            ],
            options={
                'verbose_name': 'Base',
                'verbose_name_plural': 'Bases',
            },
        ),
    ]
