# Generated by Django 2.2.7 on 2020-05-30 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_auto_20200528_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['fecha_a'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
    ]
