# Generated by Django 2.2.7 on 2020-05-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='monto',
            new_name='total',
        ),
        migrations.AddField(
            model_name='detalle',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto total del Pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal'),
        ),
    ]
