# Generated by Django 2.2.7 on 2020-05-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_auto_20200527_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
    ]
