# Generated by Django 2.2.7 on 2020-05-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_auto_20200528_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='descuento',
            field=models.FloatField(default=0.0, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='subtotal',
            field=models.FloatField(default=0.0, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='total',
            field=models.FloatField(default=0.0, verbose_name='Monto total del Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='descuento',
            field=models.FloatField(default=0.0, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='subtotal',
            field=models.FloatField(default=0.0, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.FloatField(default=0.0, verbose_name='Monto total del Pedido'),
        ),
    ]
