# Generated by Django 2.2.7 on 2020-05-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_auto_20200528_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto total del Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto total del Pedido'),
        ),
    ]
