# Generated by Django 2.2.7 on 2020-05-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_auto_20200528_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=1, verbose_name='Fecha'),
            preserve_default=False,
        ),
    ]
