# Generated by Django 2.2.7 on 2020-05-25 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('direccion', models.TextField(verbose_name='Direccion')),
                ('nit', models.CharField(max_length=10, verbose_name='Nit')),
                ('tipo_cliente', models.PositiveSmallIntegerField(choices=[('1', 'Normal'), ('2', 'Distribuidor'), ('3', 'Especial')], default=1, verbose_name='Tipo')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Contacto', verbose_name='Contacto')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
