# Generated by Django 2.2.7 on 2020-05-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contacto',
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.PositiveIntegerField(default=1, verbose_name='Telefono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('1', 'Normal'), ('2', 'Distribuidor'), ('3', 'Especial')], default='1', max_length=1, verbose_name='Tipo'),
        ),
    ]
