# Generated by Django 2.2.7 on 2020-05-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Numero')),
                ('tipo', models.PositiveSmallIntegerField(choices=[('1', 'Fijo'), ('2', 'Movil')], verbose_name='Tipo')),
                ('empresa', models.PositiveSmallIntegerField(choices=[('1', 'Claro'), ('2', 'Movistar'), ('3', 'Tigo')], verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
