# Generated by Django 2.2.7 on 2020-05-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
