# Generated by Django 2.2.7 on 2020-05-26 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Salario')),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpi', models.CharField(max_length=15, verbose_name='DPI')),
                ('foto', models.ImageField(upload_to='', verbose_name='Fotografia')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('direccion', models.TextField(verbose_name='Direccion')),
                ('nit', models.CharField(max_length=9, verbose_name='NIT')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.Puesto', verbose_name='Puesto')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
