# Generated by Django 2.2.7 on 2020-05-27 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puesto',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
