# Generated by Django 2.2.7 on 2020-05-27 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20200527_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.Puesto', verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Puesto'),
        ),
    ]
