# Generated by Django 2.2.7 on 2020-05-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_auto_20200527_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='dpi',
            field=models.CharField(max_length=15, unique=True, verbose_name='DPI'),
        ),
    ]
